# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Pedro Jordano Lab"
title_separator          : "-"
name                     : &name "Pedro Jordano"
description              : &description "Assistant Professor, School of Criminal Justice and Criminology, Texas State University"
url                      : "https://PJordano-Lab.github.io"
baseurl                  : ""
repository               : "pedroj/PJordano-Lab.github.io"

# Site Author
author:
  avatar           : "headshot.jpeg"
  name             : "Pedro Jordano"
  pronouns         :
  bio              : "Research professor, CSIC, and Associate professor, Univ. Sevilla. My research focuses on the study of biological diversity (biodiversity) from both ecological and evolutionary perspectives. I am interested in how ecological interactions, e.g. mutualisms, shape complex ecological systems. Interactions, such as those among plants and their seed dispersers and pollinators, are the wireframe of biodiversity, yet we are far from understanding how they evolve and coevolve. My main research tools to address this fascinating theme include field ecology, molecular genetics, and theoretical ecology."
  location         : "Sevilla, Spain"
  employer         : "Estación Biolólogica de Doñana, CSIC, and University of Sevilla"
  uri              :
  email            : "jordano@ebd.csic.es"

  # Academic websites
  academia         : "https://independent.academia.edu/PedroJordano"
  arxiv            :
  googlescholar    : "https://scholar.google.es/citations?hl=en&user=TrKYqaEAAAAJ"
  wos              : "https://www.webofscience.com/wos/author/record/A-5162-2008"
  impactstory      : "https://profiles.impactstory.org/u/0000-0003-2142-9116"
  orcid            : "https://orcid.org/0000-0003-2142-9116"
  semantic         :
  pubmed           :
  researchgate     : "https://www.researchgate.net/profile/Pedro-Jordano-2?ev=hdr_xprf"
  scopus           : "https://www.scopus.com/authid/detail.uri?authorId=6701660089"
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "pedroj"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          : "@pedro-jordano.bsky.social"
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : ""
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          : "pedro_jordano"
  vine             :
  weibo            :
  wikipedia        : ""
  xing             :
  youtube          :
  zhihu            :

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :
atom_feed:
  hide                   : false
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "pedro_jordano"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
og_description           :
social:
  type                   :
  name                   :
  links:

# Analytics
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
  - data/
  - research/
  - "*.Rmd"
  - call-scholar-stats.R
  - requirements.txt
  - open-alex.R
  - save_pubs.R
  - fetch-scholar-stats.py
  - _publications.yml
  - archive/
  - teaching/
  - website.Rproj
keep_files:
  - .git
  - .svn
  - CNAME
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-scholar

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-scholar

# Jekyll Scholar
scholar:
  last_name: [Jordano]
  first_name: [Pedro]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
