---
title: ""
pagetitle: "Molecular ecology of seed and pollen dissemination by animals"
page-layout: full
---

::: page-hero-slim
<p class="hero-affiliation">

Sevilla, Spain

</p>

# Molecular ecology of seed and pollen dissemination by animals

<p>Using molecuar genetics tools to assess the functional aspects and outcomes
of plant-animal interactions.</p>
:::

Plants stand still, but their genes move- rephrasing the title of a BES
symposium held in Aug 2000. And for many plant species this movement is the
result of mutualistic interactions with pollinators and frugivores. A
long-standing challenge in studies of seed dispersal by animal frugivores has
been the characterization of the spatial relationships between dispersed seeds
and the maternal plants, i.e., the seed shadow. The difficulties to track
unambiguously the origin of frugivore-dispersed seeds in natural communities has
been considered an unavoidable limitation of the research field and precluded a
robust analysis of the direct consequences of zoochory.

## Team

## Key questions

-   Together with José A. Godoy and Cristina García, we are using the multilocus
    genotype at SSR (microsatellite) loci of the woody endocarp, a seed tissue
    of maternal origin, to provide an unequivocal genetic fingerprint of the
    source tree. We have the help of JuanMi Arroyo and Cristina Rigueiro,
    technicians at the lab. By comparing the endocarp genotype against the
    complete set of genotypes of reproductive trees in a population, we were
    able to unambiguously identify the source tree for 79.7 % of the seeds
    collected in seed traps and hypothesized that the remaining 20.3 % of
    sampled seeds come from other populations.
-   Identification of the source tree for *Prunus mahaleb* seeds dispersed by
    frugivores revealed a marked heterogeneity in the genetic composition of the
    seed rain in different microhabitats, with a range of 1-5 distinct maternal
    trees contributing seeds to a particular landscape patch. Within-population
    dispersal distances ranged between 0-1112 m, with up to 62 % of the seeds
    delivered within 15 m of the source trees. We are interested in the
    ecological and evolutionary implications of our results, indicating strong
    distance limitation of seed delivery combined with infrequent long-distance
    dispersal events, extreme heterogeneity in the landscape pattern of genetic
    makeup, and a marked mosaic of multiple parentage for the seeds delivered to
    a particular patch. A detailed description of our field methods and lab
    protocols is available here.
-   Together with Arndt Hampe and Rémy Petit we are investigating how seed
    dispersal by animals influences plant population genetic structure and its
    geographic patterns. We have a bilateral agreement between MEC and the INRA
    that funds this collaboration, including an exchange program between our
    labs. With Arndt we investigate how dispersal processes influence the
    persistence of relict tree populations at their rear-edge limit of their
    distributions in Europe. For these tree species (mainly oaks), pollen and
    seed dispersal are central for the maintenance of large scale patterns of
    genetic diversity. We are interested in assessing how gene flow patterns
    have contributed and contribute to regional diversity of genetic pools.
-   New projects directed by Alfredo Valido investigate the consequences of
    dispersal processes- especially seed dispersal- for endemic Canary Island
    plant species. In the Canary Islands, many fleshy-fruited plants depend on
    lizards for their successful dispersal and recruitment. We are now working
    in a project directed by Alfredo Valido to analyze the movement ecology of
    Canarian endemic *Gallotia* lizards and its consequences for plant dispersal
    and recruitment. We study the reproductive ecology of orijama plants
    *Neochamaelea pulverulenta*, an endemic Rutaceae in the islands, whose seeds
    are exclusively dispersed by the lizards. We combine studies of fine- and
    medium-scale genetic structure with data and models of foraging movements of
    the lizards, monitoring with radio-tracking methods. So far the results are
    superb, and we now have detailed data on movement patterns of *Gallotia
    galloti* in Teno Bajo (Tenerife)- our main study site- and *G. stehlini* (in
    the photo) in Barranco de Veneguera (Gran Canaria). We have also seeds
    samples from two 1.2 ha plots in the two sites as well as leaf samples from
    \>2000 plants to assess seed dispersal patterns with genetic methods,
    similar to those that we’ve been using with *Prunus mahaleb* and *Frangula
    alnus*. We are interested in assessing the potential effects of previous
    extinctions of other giant lizard species (e.g., *G. goliath*) that were
    very good dispersers of orijama. These were up to 1.3 m long and able to
    disperse even the largest fruits and seeds of orijama, which now remain
    undispersed on the plants; only the smaller fruits and seeds remain
    dispersed by the extant smaller lizards.

## Publications